# Generated by Django 4.0.3 on 2022-04-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='destiny',
            field=models.CharField(choices=[('WT', 'Wallet'), ('EP', 'Exchange point'), ('FT', 'Fiat'), ('SW', 'somewhere')], default='SW', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='origin',
            field=models.CharField(choices=[('WT', 'Wallet'), ('EP', 'Exchange point'), ('FT', 'Fiat'), ('SW', 'somewhere')], default='SW', max_length=255),
        ),
    ]
