# Generated by Django 4.0.3 on 2022-04-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='currently_token_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='token_aumont',
            field=models.FloatField(),
        ),
    ]
