# Generated by Django 4.0.3 on 2022-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactions_currently_token_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='currently_token_price',
            field=models.FloatField(),
        ),
    ]
