# Generated by Django 4.0.3 on 2022-04-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coins',
            fields=[
                ('coin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coin_abbreviation', models.CharField(max_length=10)),
                ('coin_name', models.CharField(max_length=255)),
                ('fundation', models.DateField(blank=True)),
                ('total_amount', models.PositiveBigIntegerField(blank=True)),
                ('when_gets_one_dollar', models.DateField(blank=True)),
                ('solution', models.CharField(blank=True, max_length=100)),
                ('balance', models.CharField(blank=True, max_length=100)),
                ('is_stablecoin', models.BooleanField(default=False)),
            ],
        ),
    ]
