# Generated by Django 4.0.3 on 2022-04-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coins',
            old_name='balance',
            new_name='balance_equity',
        ),
    ]
