# Generated by Django 4.0.3 on 2022-04-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_rename_balance_coins_balance_equity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='is_stablecoin',
            field=models.BooleanField(default=True),
        ),
    ]
