# Generated by Django 4.0.3 on 2022-04-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_alter_coins_is_stablecoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='is_stablecoin',
            field=models.BooleanField(default=False),
        ),
    ]
