# Generated by Django 4.0.3 on 2022-04-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_alter_coins_is_stablecoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
