# Generated by Django 4.0.3 on 2022-04-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tokens',
            fields=[
                ('token_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('token_name', models.CharField(max_length=255)),
                ('fundation_year', models.PositiveSmallIntegerField(blank=True)),
                ('total_aumont', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
    ]
