# Generated by Django 4.0.3 on 2022-04-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='total_aumont',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
